apiVersion: v1
kind: Secret
metadata:
  name: {{ template "vault.fullname" . }}-key
  labels:
    app.kubernetes.io/name: {{ template "vault.fullname" . }}
    helm.sh/chart: {{ include "vault.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  google-service-account.json: "{{ .Values.vault.gcp.service_account_key }}"